### ISSUE TITLE
Unable to connect Monero node to GUI Wallet.

### ISSUE THREAD

**Issue by ArnoldvonMoger** [dappnode/DAppNodePackage-monero#23]
I have tried going to packages > Monero > Network and used my "Container IP" and default port (18081) to setup a remote node on the Monero GUI wallet, but it never connects. My IP address is blurred out. This also fails to connect if I try port 18080.

![image](https://user-images.githubusercontent.com/67572066/159107581-ccf4777e-db8a-4135-89c4-75f90f001c55.png)

It also failed to connect if I use the HTTPs domain mapping.

![image](https://user-images.githubusercontent.com/67572066/159107628-053fb650-0f16-43c0-a3ee-11830613ab0f.png)

Here are my Monero network settings:

![image](https://user-images.githubusercontent.com/67572066/159107644-fa79c6e5-8720-481b-b608-14e089918b52.png)

I pass the UPnP checks with all green checkmarks, as I have UPnP enabled on my router as well as manually opening the ports for 18080, 18081, 18082.

And my Monero node is fully synced.

![image](https://user-images.githubusercontent.com/67572066/159107690-82405cc4-618f-484e-879a-5ac74d9d65be.png)

I am stumped as for what to do next. I would love to have a solution for this to actually connect to my own node. Thanks.

**Comment by ArnoldvonMoger** [comment]
I have confirmed that I am connect to the node using the Container IP and the port 18081, but only while connected to DAppNode via Wireguard. I am still unable to connect via HTTPS domain mapping.

**Comment by 3alpha** [comment]
Hey, so I noticed two issues.
First, predefined port in mapping is wrong. So you have to remove it and manually 18081 to the subdomain you like. We need to fix that.
Second, in wallet GUI port should be 443.

With those settings, I managed to get it working.

**Comment by ArnoldvonMoger** [comment]
> Hey, so I noticed two issues. First, predefined port in mapping is wrong. So you have to remove it and manually 18081 to the subdomain you like. We need to fix that. Second, in wallet GUI port should be 443.
> 
> With those settings, I managed to get it working.

I made the changes you suggested and I still cannot connect to it.

![image](https://user-images.githubusercontent.com/67572066/159278669-8209b67c-a03c-4893-8e19-2b3f4c0f6524.png)
![image](https://user-images.githubusercontent.com/67572066/159278856-1bce2063-61d9-4f23-bc1c-a46ce98544f7.png)

**Comment by 3alpha** [comment]
Hey!
We can continue this on Discord since it is better communication channel annd I couldn't replicate your issue.

**Comment by alexpeterson91** [comment]
im Voss and @3alpha is Luka
